### ISSUE TITLE
ImportError: cannot import name 'Entities'

### ISSUE THREAD

**Issue by empty-id** [CheriseZhu/RSHN#1]
Hi, I set an environment denoted in readme. However, I met the following error when I ran RSHN.py:

```bash
Traceback (most recent call last):
  File "RSHN.py", line 6, in <module>
    from torch_geometric.datasets import Entities
ImportError: cannot import name 'Entities'
```

**Comment by CheriseZhu** [comment]
The 'Entities' is extracted from torch_geometric and rearranged in this directory ./torch_geometric. So, you can import it directly from this fold.

**Comment by empty-id** [comment]
Duplicate https://github.com/CheriseZhu/RSHN/issues/2
