### ISSUE TITLE
Which version of torch_geometric is needed?

### ISSUE THREAD

**Issue by empty-id** [CheriseZhu/RSHN#2]
Hi, I can't run your code normally.

When I setup "torch_geometric==1.0.0" as suggested in readme, I met

```
Traceback (most recent call last):
  File "RSHN.py", line 6, in <module>
    from torch_geometric.datasets import Entities
ImportError: cannot import name 'Entities'
```

When I setup other torch_geometric version, I met

```
Traceback (most recent call last):
  File "RSHN.py", line 7, in <module>
    from torch_geometric.nn import NNConv, RelationConv
ImportError: cannot import name 'RelationConv'
```

**Comment by CheriseZhu** [comment]
The 'RelationConv' is implemented in the fold ./torch_geometric/nn/conv, and 'Entities' can be imported from torch_geometric/dataset. Not from the original package.

**Comment by empty-id** [comment]
Yeah, I see the code. But I am still confused about how to modify the code to make it run?

**Comment by CheriseZhu** [comment]
You can specify the import from the local package.

**Comment by empty-id** [comment]
Yes, I tried to import from local. But failed. I also tried to google "how to import from local" but no available knowledge. Forgive my ignorance. [sad]

**Comment by CheriseZhu** [comment]
Maybe you could try PyCharm to deploy the code, which is friendly to you to make it run.

**Comment by empty-id** [comment]
Ah... It is a weird requirement... So is there no way to run it just in terminal? (What if I run code on a Linux server?)

**Comment by CheriseZhu** [comment]
Of course the code is running on Linux server, through configuring an interpreter using SSH.

**Comment by empty-id** [comment]
Yes, I use PyCharm now and it seems better. But there is still one problem: Could you specify the version of torch_sparse because now the code raises this error:

```
    out = spmm(edge_index, alpha, x.size(0), x)
TypeError: spmm() missing 1 required positional argument: 'matrix'
```

I think it's due to the version of torch_sparse mismatching.

If you could provide the version of the following four packages, it's better:

```
pip install torch-scatter
pip install torch-sparse
pip install torch-cluster
pip install torch-spline-conv
```

**Comment by CheriseZhu** [comment]
torch-scatter == 1.3.0
torch-sparse == 0.4.0
torch-cluster == 1.4.2
torch-spline-conv == 1.0.4

**Comment by empty-id** [comment]
Apologize for disturbing you again. Which version of CUDA are you using? I use the default cuda9.0 for pytorch 1.1. But I fail to install torch-sparse==0.4.0.

**Comment by empty-id** [comment]
Hi I made some modification and a pull request. Now the code can run with the latest version of torch-scatter and torch-sparse. (with torch 1.4.0 and cuda 10.1)

Maybe it's not necessary to merge my request, just provide for others' convenience.

**Comment by empty-id** [comment]
BTW, two lines of code can be added to the head of RSHN.py get away with the necessity of PyCharm:

```python
import sys
sys.path.insert(0, '../')
```

**Comment by CheriseZhu** [comment]
Thanks for the improvement, and I will consider the modification with the latest version.
